### ISSUE TITLE
Déployer seulement en cas de succès

### ISSUE THREAD

**Issue by RLesur** [MTES-MCT/parcours-r#10]
J'ai l'impression qu'il faudrait modifier cela
https://github.com/MTES-MCT/parcours-r/blob/c837ea17b63cc70bcfbdfdce05c1af168653d1f3/.travis.yml#L25
afin que le script de déploiement n'ait lieu qu'en cas de succès :

```yaml
after_success:
  - ./_deploy.sh 
```

**Comment by RLesur** [comment]
Je pense finalement qu'il y a une meilleure solution qui évite de tenter un deploy pour les PR : https://github.com/RLesur/parcours-r/commit/02e7ccabf00f1d5b5f3ed605da914aa83759da81

**Comment by strainel** [comment]
Fichier .travis.yml mis à jour en conséquence. merci @RLesur
