### ISSUE TITLE
activer le cache de travis

### ISSUE THREAD

**Issue by RLesur** [MTES-MCT/parcours-r#11]
https://github.com/RLesur/parcours-r/blob/312c0a7bb3ded4f662cbe536c880471408eaf9c6/.travis.yml#L8-L20

**Comment by strainel** [comment]
done !!

**Comment by RLesur** [comment]
@strainel tip https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by strainel** [comment]
yep 
suis allé trop vite... :/

**Comment by strainel** [comment]
après mise en cache de quelques passages, le build & déployé prennent environ 8 minutes contre 14. c'est nettement mieux et encore perfectible. challenge : passer sous la barre des 5 minutes... :)

**Comment by RLesur** [comment]
je pourrai essayer avec le test que je t'avais indiqué. Là, j'ai pas méga le temps mais n'hésite pas me le rappeler où bien à prendre ce que j'ai fait
