### ISSUE TITLE
déplacer les fichiers sha.csv dans le cache chunk

### ISSUE THREAD

**Issue by strainel** [MTES-MCT/parcours-r#13]
Bonjour,

Les fichiers CSV sont présents dans l'arborescence publiée sous la branche "gh-pages".
Ils ne sont pas nécessaires à cet endroit et pourraient être déplacés dans un répertoire ad-hoc comme pour les caches chunk.

Avis ?

**Comment by RLesur** [comment]
Exact. Il est vrai que j'ai fait ce choix pour la raison suivante: le répertoire d'output est toujours créé (et son nom est un paramètre) alors que le répertoire auxiliaire pas toujours (dans le cas général d'un bookdown). Techniquement, je ne connais pas assez le code source de bookdown pour savoir comment checker le nom de ce répertoire auxiliaire. Je ne sais pas dans quelle mesure c'est simple ou pas.
Sinon, j'aurais sans doute dû déjà le mettre en fichier caché (ça, c'est facile).
Autre option pas très coûteuse: le passer en paramètre.

**Comment by jengelaere** [comment]
La CI ne repose plus sur render_book_maybe qui utilisait ces csv.
