### ISSUE TITLE
ajouter dans le script rendre_book_maybe la possibilité de générer HTML, ePub & PDF

### ISSUE THREAD

**Issue by strainel** [MTES-MCT/parcours-r#14]
Bonsoir,

Le script ne permet pas de compiler les mêmes documents sur des formats différents (HTML, ePub et HTML). Est-il possible d'ajouter cette possibilité ?

**Comment by RLesur** [comment]
Je n'ai pas testé, mais normalement l'option `-f all` compilera l'ensemble des formats définis dans `_output.yml`. Je pense que le plus simple est de les rajouter dans ce fichier et de compiler avec `-f all`.

**Comment by strainel** [comment]
ok j'essaie

**Comment by strainel** [comment]
Travis CI KO... j'ai loupé qqch ?

**Comment by RLesur** [comment]
Ca fonctionnait en local ?

Comme ça, je dirais un pb dans `_output.yml`:
- rajoute une ligne finale vide (il n'y en a pas) https://github.com/MTES-MCT/parcours-r/commit/70b9a50319908d3adebd116f3665cc0337f4f85f#diff-35a3d85c96f59c1238ec37da2b0303ac
- vérifie que ce sont bien des espaces qui sont utilisés pour l'indentation et non des tabulations

**Comment by strainel** [comment]
Non j'ai été trop confiant. 
Cela paraissait simple. Je n'ai pas détecté d'erreurs.

**Comment by strainel** [comment]
hey
j'ai ajouté pour le m1 & le m2 la possibilité de télécharger le PDF ou le Epub. 
en revanche, nouveau pb de compilation sur le m3. la même erreur que pour le m1. 
je crois me souvenir qu'il y avait des problèmes de caractères spéciaux. mais je ne retrouve pas.... 
une idée ?

**Comment by MaelTheuliere** [comment]
Merci @strainel 
Je vais regarder. Tu as quoi comme message ?

**Comment by strainel** [comment]
Salut @MaelTheuliere tu peux consulter le

**Comment by RLesur** [comment]
ça vient du fichier `style.css` : il est mentionné pour faire le gitbook du m3 mais il n'existe pas dans m3.

**Comment by strainel** [comment]
ok je viens de l'ajouter

**Comment by RLesur** [comment]
je vois qu'il y a le même problème que j'avais pour m1 : il devait y avoir dans une version précédente un répertoire figures qui a été renommé en images mais tous les liens n'ont pas été mis à jour dans les Rmd

**Comment by strainel** [comment]
ok je corrige

**Comment by strainel** [comment]
m1 à m4 : OK
nouveau pb sur le m5 : compilation OK en HTML & pas le reste

```
label: f7_1 (with options) 
List of 4
 $ echo      : symbol T
 $ eval      : symbol T
 $ fig.height: num 5
 $ fig.width : num 8
Quitting from lines 834-855 (Valorisation-des-données.Rmd) 
Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  invalid font type
Calls: <Anonymous> ... drawDetails -> drawDetails.text -> grid.Call.graphics
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

si vous avez une idée

**Comment by MaelTheuliere** [comment]
Ca doit venir de `ggsave()`, je lui rajoute un `eval = F`

**Comment by MaelTheuliere** [comment]
en fait c'est l'utilisation de `theme_ipsum()` qui fait bugger

**Comment by MaelTheuliere** [comment]
Le problème de theme_ipsum est règlé (usage de polices spécifiques) mais maintenant ça plante sur gganimate `Error: Unsupported device`

**Comment by RLesur** [comment]
effectivement, ça paraît logique. La seule solution que je vois est de ne produire le gganimate que pour le html et pour les autres formats, mettre autre chose à la place

**Comment by MaelTheuliere** [comment]
On peut mettre une vidéo youtube dans un pdf : https://github.com/rstudio/bookdown/issues/92
une solution que je vois : 
- compiler le gganimate en local
- le stocker sur youtube
- afficher cette vidéo dnas le doc

**Comment by RLesur** [comment]
Faudrait peut-être trouver une solution, car toutes les PR sont en échec à cause de cela.

**Comment by strainel** [comment]
toujours d'actualité ? 
on peut certainement clore & ouvrir une autre issue...
