### ISSUE TITLE
Ne garder que ggplot pour les cartes

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/parcours-r#24]
- [ ] supprimer tmap ;
- [ ] modifier la partie rond proportionnelle ;
- [ ] intégrer les parties carto ggplot du module 7.

**Comment by MurielleL** [comment]
Réalisé: 
- insertion de la partie rond proportionnelle avec ggplot et **stat_sf_coordinates()**
- intégration de la partie **Ajouter une barre d'échelle et la flèche du nord** du module 7
- ajout d'une partie **Ajouter des étiquettes et du texte** avec les fonctions geom_sf_text() et geom_sf_label
- bascule de la cartographie avec tmap dans une partie 17 **Cartographie avec tmap**

**Comment by jengelaere** [comment]
Tout avait été fait, tmap a été relargué au dernier chapitre sur les ressources complémentaires
