### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by jdlom** [MTES-MCT/parcours-r#43]
Bonjour @MaelTheuliere,

J'ai repéré quelques coquilles et quelques exemples ne sont pas reproductibles.
J'aimerais donc contribué à parcours-R.

Quelles sont les règles pour contribuer ?
PR dans le sous-projet de formation associé ?

A bientôt,

**Comment by MaelTheuliere** [comment]
Bonjour @jdlom , merci et bienvenu parmi les contributeurs ! Tu peux soumettre en effet une PR vers les branches de dev des repos des modules que tu trouves ici https://github.com/MTES-MCT?q=parcours-r&type=&language=&sort=
Sinon il y a un fil ariane du groupe des référents, on cherche des volontaires pour nous rejoindre !
ça me fait penser d'ailleurs qu'il faut qu'on rédige un guide de contribution...

**Comment by jdlom** [comment]
> ça me fait penser d'ailleurs qu'il faut qu'on rédige un guide de contribution...

En effet, ca serait bien pas mal, surtout  pour les personnes inexpérimentées dans R comme moi !

> Sinon il y a un fil ariane du groupe des référents, on cherche des volontaires pour nous rejoindre !

Je me suis renseigné en effet. Après j'ai des  connaissances en programmation (notamment python) mais je suis encore juste en R. En effet, j'utilise R régulièrement que depuis peu donc je me forme. L'avantage c'est qu'il y a une multitude re ressources disponibles gratuitement.
