### ISSUE TITLE
Fermeture de rawgit - Intégration continue

### ISSUE THREAD

**Issue by RLesur** [MTES-MCT/parcours-r#5]
Bonjour,

Par pure curiosité et comme j'en ai un peu parlé ce soir à @MaelTheuliere , je me demandais quels étaient vos plans pour sortir de rawgit.
J'imagine que vous allez utiliser un service d'intégration continue. Si oui, lequel ? J'ai vu par exemple que [certains projets de votre organisation utilisaient Travis](https://travis-ci.org/MTES-MCT/camino-api).
J'ai utilisé Travis et GitLab CI pour quelques projets au cas où vous auriez besoin d'un coup de main. N'hésitez pas.

**Comment by strainel** [comment]
bonsoir Romain,

Voilà c'est fait ! non sans mal... Il reste encore des problèmes que je n'arrive pas à résoudre. Le plus impactant est celui du m3. J'arrive à générer le book sur mon poste, mais pas via Travis. 

Le message d'erreur : 
`Error in vapply(idx2, character(1), FUN = function(i) head(nms[idx > i],  : 
 values must be length 1,
 but FUN(X[[3]]) result is length 0
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> split_chapters -> vapply
In addition: There were 47 warnings (use warnings() to see them)`

https://travis-ci.org/MTES-MCT/parcours-r/builds/573142803

Si tu as une idée...

**Comment by strainel** [comment]
trouvé ! un problème d'encodage UTF8.... j'ai converti à la hache avec iconv.
02-rappels.Rmd line 164

**Comment by RLesur** [comment]
Bonsoir Stéphane,

Effectivement, je vois que ça a été un gros travail ! Bravo !

**Comment by MaelTheuliere** [comment]
Bonjour @strainel, bonjour @RLesur.
Merci Stéphane, gros boulot ! 
Cela va du coup nous incicer pas mal à utiliser github par défaut pour la suite. Pour mon info, tu as packagé le parcours aussi en plus d'avoir mis tout ça en build travis ?
Sinon je reste peu convaincu du fait de garder un seul "méta projet" pour l'ensemble des modules avec en plus un projet Rstudio pour chaque module... 
Pour moi la bonne pratique serait d'avoir un projet packagé pour chaque module et garder parcours-r pour la page d'accueil.

**Comment by RLesur** [comment]
Effectivement, tout reconstruire à chaque build est un peu coûteux. Une façon d'alléger le build tout en conservant un seul projet serait d'adopter une logique GNU make.
Mais effectivement, l'idée d'avoir un projet par module et un méta projet parcours-r semble peut-être la plus simple.

**Comment by strainel** [comment]
Avant de tout chambouler, il y a une solution type "GNU make" pour faire des builds intelligents des différents modules ?

**Comment by MaelTheuliere** [comment]
Est ce qu'une solution GNU make ne serait pas un peu trop technique pour des contributeurs lambda ?

**Comment by strainel** [comment]
l'idée serait plutôt de la mettre en place dans un projet "modèle". mais ca reste théorique, car je ne vois pas très bien comment on peut faire un "make intelligent" par module... @RLesur ??

**Comment by RLesur** [comment]
Ma suggestion de make s'appuie sur le fait que la documentation de [**bookdown**](https://github.com/rstudio/bookdown) avec travis est construite comme ça. Ensuite, sur le fait de gérer plusieurs Makefile au sein d'un même projet, j'ai ça en tête https://stackoverflow.com/a/1139313/6500804
Une fois que c'est mis en place, le contributeur lambda n'a rien à faire (à part ne pas supprimer les fichiers Makefile).
En revanche, je n'ai jamais testé make avec **bookdown**. Je vais regarder ça.

> l'idée serait plutôt de la mettre en place dans un projet "modèle". mais ca reste théorique

Il est possible d'utiliser un template RStudio, par exemple. Voir https://github.com/rstudio/bookdown/tree/master/inst/rstudio/templates/project
