### ISSUE TITLE
Ajouter les liens vers SSPCloub sur https://mtes-mct.github.io/parcours-r/

### ISSUE THREAD

**Issue by jengelaere** [MTES-MCT/parcours-r#52]
Apparemment ça ne se gère que dans le `index.html` du repos ?

**Comment by jdlom** [comment]
Oui d'après une introspection rapide que j'ai pu en faire

**Comment by jengelaere** [comment]
J'ai cherché dans l'historique des commits, et pas de trace d'un index.Rmd qui aurait été écrasé.
J'imagine que la mise en page devait soucis pour produire ça à partir d'un Rmd
C'est toi qui a créé le formations.csv ?

**Comment by MaelTheuliere** [comment]
Je confirme que ça a été développé directement en html par @strainel 
mais pourquoi pas le transformer en site avec distill ?

**Comment by jdlom** [comment]
Oui c'est une possibilité.

**Comment by strainel** [comment]
Oui c'est une page html à la main. L'idée était de faire très simple pour permettre des mises à jour tout aussi rapidement et sans grande technicité. Un simple copier coller suffit normalement.

**Comment by MaelTheuliere** [comment]
> Oui c'est une possibilité.

ça permet de rajouter un blog pour lister les nouveautés :-p

**Comment by jdlom** [comment]
> ça permet de rajouter un blog pour annoncer les nouveautés :-p

Toujours plus toujours plus
