### ISSUE TITLE
mettre le script d'installation des packages "ministère" sur github

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/parcours-r#6]
Le  script est évoqué ici : https://rawgit.com/MTES-MCT/parcours-r/master/Supports_formations/m1_socle/_book/bien-commencer.html#activer-les-packages-necessaires
Il n'y a pas de raison de le laisser sur l'intranet, il peut être public

**Comment by strainel** [comment]
Tu pourrais me renvoyer le fichier .R qui permet de mettre à jour les packages ? Pas sur de le retrouveR... merci Maël

**Comment by MaelTheuliere** [comment]
Voilà !

[preparation_pack_install_libraries.zip](https://github.com/MTES-MCT/parcours-r/files/3544857/preparation_pack_install_libraries.zip)

**Comment by strainel** [comment]
merci Maël
je viens de pousser la mise à jour & le lien est maintenant directement dans le m1 sur la page que tu indiquais. on pourra le mettre ailleurs si besoin.
