### ISSUE TITLE
Réarchitecture parcours de formation

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/parcours-r#8]
Garder dans parcours-r uniquement la page d'accueil et éclater chaque module en autant de projets distincts

**Comment by strainel** [comment]
je ferme celui-ci pour le moment. l'organisation actuelle me parait bien.

**Comment by MaelTheuliere** [comment]
Stéphane, on a discuté de ça au sein du G2R hier, le consensus s'est porté sur un éclatement des modules au vue de l'analyse cout bénéfice. Le seul inconvénient bloquant étant qu'il va falloir que nous ayons la main sur la création des repos du compte MTES. Nicolas doit prendre contact avec toi je crois à ce sujet.

**Comment by MaelTheuliere** [comment]
Travail en cours 
[ ] [module 1](https://github.com/MTES-MCT/parcours_r_socle_introduction)
[ ] [module 2](https://github.com/MTES-MCT/parcours_r_socle_preparation_des_donnees) 
[ ] [module 3](https://github.com/MTES-MCT/parcours_r_module_statistiques_descriptives) 
[ ] [module 4](https://github.com/MTES-MCT/parcours_r_module_analyse_multi_dimensionnelles) 
[ ] [module 5](https://github.com/MTES-MCT/parcours_r_module_datavisualisation) 
[ ] [module 6](https://github.com/MTES-MCT/parcours_r_module_publication_rmarkdown) 
[ ] [module 7](https://github.com/MTES-MCT/parcours_r_module_analyse_spatiale)
[ ] [banque d'exercices](https://github.com/MTES-MCT/parcours_r_exercices)

**Comment by strainel** [comment]
je n'avais pas vu que vous aviez décidé cela. je reste persuadé que ce n'est pas une bonne idée. on perd totalement la vision complète de la formation.

**Comment by MaelTheuliere** [comment]
Non, on garde la vision complète car parcours-r continue d'exister pour la page d'accueil, qui renvoi vers chacun des repos. C'est bien  plus facile à gérer. Par exemple pour les chaines travis, la versionisation des modules qui ne sera pas synchrone... Et ça permet à chacun de contribuer sur son domaine de compétence sans avoir à forker les 10 modules.

**Comment by strainel** [comment]
Pas convaincu : vous cassez la dynamique de groupe qui prévalait. Vous créez des silos par module et donc par contributeurs, alors qu'il fallait unifier les contributions.

**Comment by MaelTheuliere** [comment]
Salut Stéphane, on peut s'appeler pour échanger ce sera peut être plus simple que par écrit ? Mon numéro du bureau fonctionne avec le renvoi d'appel : 02 72 74 74 50

**Comment by jengelaere** [comment]
Eclatement des modules réalisés.
